//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/PawnGameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/PawnGameInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PawnGameInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PawnGameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PawnGameInput"",
    ""maps"": [
        {
            ""name"": ""PawnGame"",
            ""id"": ""094e6d4b-4068-4541-927e-144320c5f10c"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""35732433-7b4f-421c-acff-9028b12f754d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraToggle"",
                    ""type"": ""Button"",
                    ""id"": ""4272f627-760e-48d1-8606-eb09262665c6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7d65e4d1-0ba0-42d9-9448-4bff28948cab"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3398c6b-ce00-452c-a35d-418f4e3068d4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FreeCamMove"",
            ""id"": ""cd81ac26-5523-42a2-a949-13ce26c57091"",
            ""actions"": [
                {
                    ""name"": ""FreeCamMove"",
                    ""type"": ""Value"",
                    ""id"": ""a9978831-5841-401d-a6af-4a3a2144936f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraDrag"",
                    ""type"": ""Button"",
                    ""id"": ""e361999f-2ae9-4cc1-be2d-60c4f6187a7a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""da3da9c9-90d3-416a-b10f-31a499e1d19e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeCamMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""206a4111-f443-41ca-9cae-a0913a7fd434"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeCamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""27d4df81-295c-4a15-a32c-22bf5d490d98"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeCamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6b2ffa99-b547-4dfa-a4b2-0eb055b3d826"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeCamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""10dd0174-0ad3-4e4b-8078-3ca480ebeb0c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeCamMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""44eeb54a-f190-42c9-9011-eb0ad0a2f33d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PawnGame
        m_PawnGame = asset.FindActionMap("PawnGame", throwIfNotFound: true);
        m_PawnGame_Click = m_PawnGame.FindAction("Click", throwIfNotFound: true);
        m_PawnGame_CameraToggle = m_PawnGame.FindAction("CameraToggle", throwIfNotFound: true);
        // FreeCamMove
        m_FreeCamMove = asset.FindActionMap("FreeCamMove", throwIfNotFound: true);
        m_FreeCamMove_FreeCamMove = m_FreeCamMove.FindAction("FreeCamMove", throwIfNotFound: true);
        m_FreeCamMove_CameraDrag = m_FreeCamMove.FindAction("CameraDrag", throwIfNotFound: true);
    }

    ~@PawnGameInput()
    {
        UnityEngine.Debug.Assert(!m_PawnGame.enabled, "This will cause a leak and performance issues, PawnGameInput.PawnGame.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_FreeCamMove.enabled, "This will cause a leak and performance issues, PawnGameInput.FreeCamMove.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PawnGame
    private readonly InputActionMap m_PawnGame;
    private List<IPawnGameActions> m_PawnGameActionsCallbackInterfaces = new List<IPawnGameActions>();
    private readonly InputAction m_PawnGame_Click;
    private readonly InputAction m_PawnGame_CameraToggle;
    /// <summary>
    /// Provides access to input actions defined in input action map "PawnGame".
    /// </summary>
    public struct PawnGameActions
    {
        private @PawnGameInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PawnGameActions(@PawnGameInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PawnGame/Click".
        /// </summary>
        public InputAction @Click => m_Wrapper.m_PawnGame_Click;
        /// <summary>
        /// Provides access to the underlying input action "PawnGame/CameraToggle".
        /// </summary>
        public InputAction @CameraToggle => m_Wrapper.m_PawnGame_CameraToggle;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PawnGame; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PawnGameActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PawnGameActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PawnGameActions" />
        public void AddCallbacks(IPawnGameActions instance)
        {
            if (instance == null || m_Wrapper.m_PawnGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PawnGameActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @CameraToggle.started += instance.OnCameraToggle;
            @CameraToggle.performed += instance.OnCameraToggle;
            @CameraToggle.canceled += instance.OnCameraToggle;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PawnGameActions" />
        private void UnregisterCallbacks(IPawnGameActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @CameraToggle.started -= instance.OnCameraToggle;
            @CameraToggle.performed -= instance.OnCameraToggle;
            @CameraToggle.canceled -= instance.OnCameraToggle;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PawnGameActions.UnregisterCallbacks(IPawnGameActions)" />.
        /// </summary>
        /// <seealso cref="PawnGameActions.UnregisterCallbacks(IPawnGameActions)" />
        public void RemoveCallbacks(IPawnGameActions instance)
        {
            if (m_Wrapper.m_PawnGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PawnGameActions.AddCallbacks(IPawnGameActions)" />
        /// <seealso cref="PawnGameActions.RemoveCallbacks(IPawnGameActions)" />
        /// <seealso cref="PawnGameActions.UnregisterCallbacks(IPawnGameActions)" />
        public void SetCallbacks(IPawnGameActions instance)
        {
            foreach (var item in m_Wrapper.m_PawnGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PawnGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PawnGameActions" /> instance referencing this action map.
    /// </summary>
    public PawnGameActions @PawnGame => new PawnGameActions(this);

    // FreeCamMove
    private readonly InputActionMap m_FreeCamMove;
    private List<IFreeCamMoveActions> m_FreeCamMoveActionsCallbackInterfaces = new List<IFreeCamMoveActions>();
    private readonly InputAction m_FreeCamMove_FreeCamMove;
    private readonly InputAction m_FreeCamMove_CameraDrag;
    /// <summary>
    /// Provides access to input actions defined in input action map "FreeCamMove".
    /// </summary>
    public struct FreeCamMoveActions
    {
        private @PawnGameInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FreeCamMoveActions(@PawnGameInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "FreeCamMove/FreeCamMove".
        /// </summary>
        public InputAction @FreeCamMove => m_Wrapper.m_FreeCamMove_FreeCamMove;
        /// <summary>
        /// Provides access to the underlying input action "FreeCamMove/CameraDrag".
        /// </summary>
        public InputAction @CameraDrag => m_Wrapper.m_FreeCamMove_CameraDrag;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_FreeCamMove; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FreeCamMoveActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FreeCamMoveActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FreeCamMoveActions" />
        public void AddCallbacks(IFreeCamMoveActions instance)
        {
            if (instance == null || m_Wrapper.m_FreeCamMoveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FreeCamMoveActionsCallbackInterfaces.Add(instance);
            @FreeCamMove.started += instance.OnFreeCamMove;
            @FreeCamMove.performed += instance.OnFreeCamMove;
            @FreeCamMove.canceled += instance.OnFreeCamMove;
            @CameraDrag.started += instance.OnCameraDrag;
            @CameraDrag.performed += instance.OnCameraDrag;
            @CameraDrag.canceled += instance.OnCameraDrag;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FreeCamMoveActions" />
        private void UnregisterCallbacks(IFreeCamMoveActions instance)
        {
            @FreeCamMove.started -= instance.OnFreeCamMove;
            @FreeCamMove.performed -= instance.OnFreeCamMove;
            @FreeCamMove.canceled -= instance.OnFreeCamMove;
            @CameraDrag.started -= instance.OnCameraDrag;
            @CameraDrag.performed -= instance.OnCameraDrag;
            @CameraDrag.canceled -= instance.OnCameraDrag;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FreeCamMoveActions.UnregisterCallbacks(IFreeCamMoveActions)" />.
        /// </summary>
        /// <seealso cref="FreeCamMoveActions.UnregisterCallbacks(IFreeCamMoveActions)" />
        public void RemoveCallbacks(IFreeCamMoveActions instance)
        {
            if (m_Wrapper.m_FreeCamMoveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FreeCamMoveActions.AddCallbacks(IFreeCamMoveActions)" />
        /// <seealso cref="FreeCamMoveActions.RemoveCallbacks(IFreeCamMoveActions)" />
        /// <seealso cref="FreeCamMoveActions.UnregisterCallbacks(IFreeCamMoveActions)" />
        public void SetCallbacks(IFreeCamMoveActions instance)
        {
            foreach (var item in m_Wrapper.m_FreeCamMoveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FreeCamMoveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FreeCamMoveActions" /> instance referencing this action map.
    /// </summary>
    public FreeCamMoveActions @FreeCamMove => new FreeCamMoveActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PawnGame" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PawnGameActions.AddCallbacks(IPawnGameActions)" />
    /// <seealso cref="PawnGameActions.RemoveCallbacks(IPawnGameActions)" />
    public interface IPawnGameActions
    {
        /// <summary>
        /// Method invoked when associated input action "Click" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraToggle(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "FreeCamMove" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FreeCamMoveActions.AddCallbacks(IFreeCamMoveActions)" />
    /// <seealso cref="FreeCamMoveActions.RemoveCallbacks(IFreeCamMoveActions)" />
    public interface IFreeCamMoveActions
    {
        /// <summary>
        /// Method invoked when associated input action "FreeCamMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFreeCamMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraDrag" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraDrag(InputAction.CallbackContext context);
    }
}
